spring:
  data:
    mongodb:
#      username: nipuna
#      password: nipuna
      host: localhost
      port: 27017
      database: micro-customer
#      authentication-database: admin
server:
  port: 8090